import random

def main():
	animales = ["la abeja",
"el águila",
"el alce",
"la almeja",
"la alondra",
"la anchoa",
"la anguila",
"el antílope",
"la araña",
"la ardilla",
"el arenque",
"la atún",
"el avestruz",
"la avispa",
"la babosa",
"el bacalao",
"la ballena",
"el buey",
"el búfalo",
"el búho",
"el buitre",
"el burro",
"la caballa",
"el caballito de mar",
"el caballo",
"la cabra",
"la cacatúa",
"el caimán",
"el calamar",
"el camaleón",
"el camarón",
"el camello",
"el canario",
"el cangrejo",
"el canguro",
"el caracol",
"el castor",
"la cebra",
"el cerdo",
"el chacal",
"el chimpancé",
"la chinche",
"el ciempiés",
"el ciervo",
"la cigarra",
"la cigüeña",
"el cisne",
"la cobaya",
"el cocodrilo",
"la codorniz",
"el colibrí",
"la comadreja",
"el cóndor",
"el conejo",
"el correcaminos",
"la cucaracha",
"el cuervo",
"el delfín",
"el dromedario",
"el elefante",
"el erizo",
"el escarabajo",
"el escorpión",
"la estrella de mar",
"el faisán",
"el flamenco",
"la foca",
"la gacela",
"la gallina",
"la gallo",
"la gamba",
"el ganso",
"la garrapata",
"el gato",
"el gavilán",
"la gaviota",
"la golondrina",
"el gorila",
"el gorrión",
"el grillo",
"la grulla",
"el guepardo",
"el gusano",
"el halcón",
"la hiena",
"el hipopótamo",
"la hormiga",
"el hurón",
"la urraca",
"la iguana",
"el jabalí",
"el jaguar",
"el jilguero",
"la jirafa",
"el koala",
"la lagartija",
"la langosta",
"el lenguado",
"el león",
"el león marino",
"el leopardo",
"la libélula",
"la liebre",
"el lince",
"la llama",
"el lobo",
"la lombriz",
"el loro",
"la luciérnaga",
"el mamut",
"el manatí",
"el mandril",
"la mantis religiosa",
"el mapache",
"la mariposa",
"la mariquita",
"la marmota",
"la medusa",
"el mejillón",
"el mirlo",
"la mofeta",
"el mono",
"la morsa",
"la mosca",
"la mula",
"el murciélago",
"la nutria",
"la orca",
"la oruga",
"el oso",
"el oso hormiguero",
"el oso panda",
"el oso perezoso",
"el oso polar",
"la ostra",
"la oveja",
"el pájaro",
"el pájaro carpintero",
"la paloma",
"la pantera",
"el pato",
"el pavo",
"el pavo real",
"el pelícano",
"la perdiz",
"el perro",
"el petirrojo",
"el pez espada",
"el pescado",
"el pingüino",
"la polilla",
"el pollo",
"el poni",
"el potro",
"el puercoespín",
"la pulga",
"el pulpo",
"el puma",
"la rana",
"la rata",
"el ratón",
"la raya",
"el reno",
"el rinoceronte",
"el ruiseñor",
"la salamandra",
"el salmón",
"el saltamontes",
"la sanguijuela",
"el sapo",
"la sardina",
"la serpiente",
"el tapir",
"el tejón",
"el ternero",
"el tiburón",
"el tigre",
"el topo",
"el toro",
"la tortuga",
"el tritón",
"la trucha",
"el tucán",
"la vaca",
"la víbora",
"el visón",
"la yegua",
"la zorra",
"el zorro",]
	verbos = ["acariciar", "consultar", "trabajar", "animar", "ensuciar", "sacudir", "lustrar", "pulir", "encerar", "desmembrar", "degollar", "aplaudir", "educar", "ayudar"]
	
	for i in range(20):
		print(random.choice(verbos) + " " + random.choice(animales))
 

if __name__== "__main__":
	main()